"""empty message

Revision ID: 27826b9594da
Revises: 4e0387688a79
Create Date: 2013-12-04 16:53:39.269000

"""

# revision identifiers, used by Alembic.
revision = '27826b9594da'
down_revision = '4e0387688a79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_ip', sa.String(length=64), nullable=True),
    sa.Column('public_ip_secondary', sa.String(length=64), nullable=True),
    sa.Column('private_ip', sa.String(length=64), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('saltversion', sa.String(length=64), nullable=True),
    sa.Column('grains', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['host_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('login', 'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('login', 'user', [u'login'], unique=True)
    op.drop_table('host')
    op.drop_table('host_group')
    ### end Alembic commands ###
