"""empty message

Revision ID: 2ea70d5368c6
Revises: None
Create Date: 2013-12-16 14:52:01.658000

"""

# revision identifiers, used by Alembic.
revision = '2ea70d5368c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=66), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_ip', sa.String(length=64), nullable=True),
    sa.Column('public_ip_secondary', sa.String(length=64), nullable=True),
    sa.Column('private_ip', sa.String(length=64), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('saltversion', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['host_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_grains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_grains')
    op.drop_table('host')
    op.drop_table('user')
    op.drop_table('host_group')
    ### end Alembic commands ###
